//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneSistem.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class libraryDBEntities : DbContext
    {
        public libraryDBEntities()
            : base("name=libraryDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KITAP> KITAP { get; set; }
        public virtual DbSet<OGRENCI> OGRENCI { get; set; }
        public virtual DbSet<TUR> TUR { get; set; }
        public virtual DbSet<YAZAR> YAZAR { get; set; }
        public virtual DbSet<ISLEM> ISLEM { get; set; }
    }
}
