//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneSistem.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class YAZAR
    {
        public int yazar_no { get; set; }
        public string yazar_ad { get; set; }
        public string yazar_soyad { get; set; }
    }
}
